name: ai-for-science-agents
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - scipy=1.11.4
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - pip:
      - openai>=1.52.0
      - python-dotenv>=1.0.1
      - pydantic>=2.7.0
      - rich>=13.7.0
      - typer>=0.12.3
      - jinja2>=3.1.3
      - pyyaml>=6.0.1
      - markdown>=3.6
      - tenacity>=8.3.0
      - tiktoken>=0.7.0
      - duckduckgo-search>=5.3.0
      - pandas>=2.2.2
